
auto-fill-login-username: true


is-login-code: true




server:
    port: 8083
    servlet:

        context-path: /product


spring:

    datasource:

        url: jdbc:mysql://127.0.0.1:3306/db_product?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root

        password: Cz5079010
        driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:

            write-dates-as-timestamps: true
    mvc:

        throw-exception-if-no-handler-found: true
    servlet:
        multipart:

            max-file-size: 500MB
            max-request-size: 500MB
    web:
        resources:

            static-locations:
                - classpath:/static/
                - file:${user.dir}/ 

    mail:

        host: smtp.qq.com
        username: 3840533516@qq.com

        password: gxukqxtqrwcoceeb

        defaultEncoding: utf-8
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        enable: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory





mybatis:

    mapper-locations: classpath:mappers/*.xml

    type-aliases-package: com.entity

    configuration:

        map-underscore-to-camel-case: false
        cache-enabled: false
        call-setters-on-nulls: true

        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
    level:
        com:

            org:
                springframework: debug




